
[profile.default]
solc_version = '0.8.15'
auto_detect_solc = false
optimizer = true
optimizer_runs = 200 # Default amount
ffi = true
fuzz_runs = 1_000
remappings = [
  "forge-std=lib/forge-std/src/",
  "foundry-huff=lib/foundry-huff/src/",
]
[profile.default.rpc_endpoints]
eth = 'https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}'
